name: Tool/deepxctl Build
on: [push, pull_request]
 
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04]  # 只保留 Ubuntu
        go-version: [1.23.2]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    # 系统依赖安装
    - name: 安装Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
        cache: true

    # 系统依赖安装
    - name: 安装依赖 (Ubuntu)
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get install -y git

    # 构建deepxctl工具
    - name: 构建deepxctl
      run: |
        cd tool/deepxctl
        go build -v -o deepxctl
    
    # 运行测试
    - name: 运行测试
      run: |
       cd tool/deepxctl
       ./deepxctl
 